#! /bin/sh
CODERESET="\033[0m"
LINECOLOR="$CODERESET\033[38;5;33m"
LINEEND="$CODERESET"
HIGHLIGHT="$CODERESET\033[1;38;5;184m"
HIGHLIGHTEND="$CODERESET$LINECOLOR"

if [ "$1" == "" ]; then
	BRANCH=$(git rev-parse --abbrev-ref HEAD)
else
	BRANCH=$(git rev-parse $1)
fi

if [ "$2" == "" ]; then
	MASTER=master
else
	MASTER="$2"
fi

BASE_COMMIT=$(git log --format="%P" "$BRANCH" ^"$MASTER" | tail -n 1)

if [ "$BASE_COMMIT" == "" ]; then
	echo "$LINECOLOR* Branch does not diverge from $MASTER!$LINEEND"
	exit
fi

echo "$LINECOLOR* Base commit is $HIGHLIGHT$BASE_COMMIT$HIGHLIGHTEND$LINEEND"
git diff $BASE_COMMIT $BRANCH
echo "\n$LINECOLOR* $HIGHLIGHT""Done.""$HIGHLIGHTEND$LINEEND"
